In [ ]:
!pip install dvc
!pip install dvc[http]
!git clone https://github.com/Nhattk19/sentiment-dvc-code.git

In [ ]:
%cd sentiment-dvc-code
!ls -R

In [ ]:
with open("/content/token.txt", "r") as f:
    token = f.read().strip()
!dvc remote modify dagshub auth basic
!dvc remote modify dagshub user Nhattk19
!dvc remote modify dagshub password token

In [ ]:
!dvc pull
!ls data/raw

Collecting          |1.00 [00:00,  122entry/s]
Fetching
!
  0% |          |0/? [00:00<?,    ?files/s]
Fetching
Building workspace index          |3.00 [00:00,  857entry/s]
Comparing indexes          |4.00 [00:00,  933entry/s]
Applying changes          |1.00 [00:00,   147file/s]
M       data/raw/sentiment.csv
1 file modified
sentiment.csv  sentiment.csv.dvc

In [ ]:
import pandas as pd

df = pd.read_csv("data/raw/sentiment.csv")
df.head()

                  text      label
0    I love this movie   positive
1    This was terrible   negative
2  Pretty good overall   positive
3        Waste of time   negative
4  Amazing performance   positive

In [ ]:
!git log --oneline

01acc06 (HEAD -> main, origin/main, origin/HEAD) Dataset v2: added more rows
e13fff0 Track sentiment dataset v1
8e122bc Add DagsHub remote storage
572f4bf Initialize Git and DVC

In [ ]:
!git checkout e13fff0
!dvc pull

M	.dvc/config
HEAD is now at e13fff0 Track sentiment dataset v1
Collecting          |0.00 [00:00,    ?entry/s]
Fetching
!
  0% |          |0/? [00:00<?,    ?files/s]
Fetching
Building workspace index          |3.00 [00:00,  777entry/s]
Comparing indexes          |4.00 [00:00, 1.01kentry/s]
Applying changes          |0.00 [00:00,     ?file/s]
Everything is up to date.

In [ ]:
df = pd.read_csv("data/raw/sentiment.csv")
df.head()

                  text      label
0    I love this movie   positive
1    This was terrible   negative
2  Pretty good overall   positive
3        Waste of time   negative